from setuptools import setup, find_packages

version = '0.1'

setup(name='plone.app.upgrade',
      version=version,
      description="Upgrade machinery for Plone.",
      long_description=open("README.txt").read() + "\n" +
                       open("CHANGES.txt").read(),
      classifiers=[
        'Framework :: Plone',
      ],
      keywords='Plone upgrade migration',
      author='Plone Foundation',
      author_email='plone-developers@lists.sourceforge.net',
      url='http://pypi.python.org/pypi/plone.app.upgrade',
      license='GPL',
      packages=find_packages(exclude=['ez_setup']),
      namespace_packages = ['plone', 'plone.app'],
      include_package_data=True,
      zip_safe=False,
      extras_require=dict(
        test=[
            'Products.PloneTestCase',
            'plone.contentrules',
            'plone.app.i18n',
            'plone.app.redirector',
            'plone.app.viewletmanager',
            'zope.app.cache',
            'Products.kupu',
        ]
      ),
      install_requires=[
        'setuptools',
        'five.localsitemanager',
        'plone.portlets',
        'plone.session',
        'plone.app.portlets',
        'zope.component',
        'zope.app.component',
        'Plone',
        'Products.Archetypes',
        'Products.ATContentTypes',
        'Products.CMFActionIcons',
        'Products.CMFCalendar',
        'Products.CMFCore',
        'Products.CMFDefault',
        'Products.CMFDiffTool',
        'Products.CMFEditions',
        'Products.CMFFormController',
        'Products.CMFPlacefulWorkflow',
        'Products.CMFQuickInstallerTool',
        'Products.CMFUid',
        'Products.DCWorkflow',
        'Products.GenericSetup',
        'Products.MimetypesRegistry',
        'Products.PloneLanguageTool',
        'Products.PlonePAS',
        'Products.PortalTransforms',
        'Products.ResourceRegistries',
        # 'Acquisition',
        # 'Zope2',
      ],
      )
